name: Sheet to Json Workflow

on:
  schedule:
    # every 10 minutes the job will run
    - cron:  '*/10 * * * *'
  push:
    branches:
      - master

jobs:
  update-json-data:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v1
      - name: push
        run: |
           bash ./pushthejson
           echo "the job completed"
        env:
            GITHUB_TOKEN: ${{ secrets.github_token }}
            BOT_TOKEN: ${{ secrets.bot_token }}
            SHEET_ID: ${{ secrets.SHEET_ID }}
            RESOURCES_SHEET_ID: ${{ secrets.RESOURCES_SHEET_ID }}
            STUCK_BOT: ${{ secrets.STUCK_BOT }} 
      - name: show job status
        if: always()
        run: node lib/notify_tg.js $STUCK_BOT $status 
        env: 
          status: ${{job.status}}
          STUCK_BOT: ${{ secrets.STUCK_BOT }} 


#trigger the action
#trigger the action by remove this line
